name: Build Status

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      - name: Install Node dependencies
        run: npm install
      - name: Prepare .env file
        run: |
            if [ -f .env ]; then
              echo ".env already present, skipping."
            elif [ -f .env.example ]; then
              cp .env.example .env
              echo "Copied .env.example → .env"
            else
              echo "No .env or .env.example found, skipping."
            fi
      - name: Run Node lints
        run: |
            if [ -f package.json ] && grep -q "\"lint\"" package.json; then
              npm run lint
            else
              echo "No lint script or no JS files; skipping frontend lint"
            fi
      - name: Run Python lints
        run: flask lint --check
      - name: Run Python tests
        run: flask test